name: Update README daily

on:
  schedule:
    - cron: '00 7 * * *'
  push:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Update README.md
        run: node index.js

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Iovann
          author_email: iovannatcho@gmail.com
          message: ':memo: README.md updated by Gabot'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
